### ISSUE TITLE
kl divergence loss of GumbelQuantize

### ISSUE THREAD

**Issue by jjjjohnson** [karpathy/deep-vector-quantization#3]
Hi Andrej!
I have a hard time understanding the loss of kl divergence to the prior. Where does it come from? Does it mean we assume the prior is a uniform distribution with prob = 1/self.n_embed ? 
https://github.com/karpathy/deep-vector-quantization/blob/53ef953d1d853f776d4455432ce3ca05e30805ae/model.py#L99

Thanks for any hints!

**Comment by karpathy** [comment]
Hi, yes the natural prior to use over a categorical is simply uniform. I skipped a step or two on this line but basically we are evaluating the second term of the ELBO in the VAE objective (the first is just the reconstruction), which is just the KL divergence between the posterior (qy) and the prior. However, because the prior is just a uniform with probability `1/self.n_embed`, dividing by it in the KL divergence equation is simply equal to multiplying by `self.n_embed`. I'd search for tutorials on VAE, ELBO, and refer to the KL divergence formula on Wikipedia.
