### ISSUE TITLE
What is data-driven intialization scheme with k-means?

### ISSUE THREAD

**Issue by kritiagg** [karpathy/deep-vector-quantization#5]

**Comment by karpathy** [comment]
It's implemented here: https://github.com/karpathy/deep-vector-quantization/blob/main/model.py#L40

It "closed form" solves the vector quantization problem at initialization (only approximately because it's just on the first batch), instead of waiting for gradients to slowly move the cluster embeddings towards data during training. It's all kind of janky because VQ objective is not the same as the KL divergence of the posterior to (uniform) prior, but alright.

**Comment by GuangtaoLyu** [comment]
> It's implemented here: https://github.com/karpathy/deep-vector-quantization/blob/main/model.py#L40
> 
> It "closed form" solves the vector quantization problem at initialization (only approximately because it's just on the first batch), instead of waiting for gradients to slowly move the cluster embeddings towards data during training. It's all kind of janky because VQ objective is not the same as the KL divergence of the posterior to (uniform) prior, but alright.

Is there a reference paper for this? I want to quote it.
